appname = ruler_api
httpport = ${RULER_APP_PORT}
runmode = ${RULER_APP_RUN_MODE||prod}
autorender = false
copyrequestbody = true
EnableDocs = true
parameterStore = ${PARAMETER_STORE}
PGuser=${RULER_DB_USER}
PGpass=${RULER_DB_PASS}
PGhost=${RULER_DB_URL}
PGport=${RULER_DB_PORT}
PGdb=${RULER_DB_NAME}
PGschema=${RULER_DB_SCHEMAS}